################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ADC_program.c \
../Src/DMA_program.c \
../Src/EXTI_program.c \
../Src/GPIO_program.c \
../Src/Keypad_program.c \
../Src/LCD_program.c \
../Src/NVIC_program.c \
../Src/RCC_program.c \
../Src/SEG_program.c \
../Src/SysTick_program.c \
../Src/Timer_program.c \
../Src/UART_program.c \
../Src/main.c \
../Src/syscalls.c \
../Src/sysmem.c 

OBJS += \
./Src/ADC_program.o \
./Src/DMA_program.o \
./Src/EXTI_program.o \
./Src/GPIO_program.o \
./Src/Keypad_program.o \
./Src/LCD_program.o \
./Src/NVIC_program.o \
./Src/RCC_program.o \
./Src/SEG_program.o \
./Src/SysTick_program.o \
./Src/Timer_program.o \
./Src/UART_program.o \
./Src/main.o \
./Src/syscalls.o \
./Src/sysmem.o 

C_DEPS += \
./Src/ADC_program.d \
./Src/DMA_program.d \
./Src/EXTI_program.d \
./Src/GPIO_program.d \
./Src/Keypad_program.d \
./Src/LCD_program.d \
./Src/NVIC_program.d \
./Src/RCC_program.d \
./Src/SEG_program.d \
./Src/SysTick_program.d \
./Src/Timer_program.d \
./Src/UART_program.d \
./Src/main.d \
./Src/syscalls.d \
./Src/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Src/ADC_program.o: ../Src/ADC_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ADC_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/DMA_program.o: ../Src/DMA_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/DMA_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/EXTI_program.o: ../Src/EXTI_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/EXTI_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/GPIO_program.o: ../Src/GPIO_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/GPIO_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/Keypad_program.o: ../Src/Keypad_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/Keypad_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/LCD_program.o: ../Src/LCD_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/LCD_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/NVIC_program.o: ../Src/NVIC_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/NVIC_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/RCC_program.o: ../Src/RCC_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/RCC_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/SEG_program.o: ../Src/SEG_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/SEG_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/SysTick_program.o: ../Src/SysTick_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/SysTick_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/Timer_program.o: ../Src/Timer_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/Timer_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/UART_program.o: ../Src/UART_program.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/UART_program.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/main.o: ../Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/main.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/syscalls.o: ../Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/syscalls.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Src/sysmem.o: ../Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32 -DSTM32F1 -DSTM32F103C8Tx -DDEBUG -c -I../Inc -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/ADC1_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/Keypad_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/EXT_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/GPIO_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/LCD_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/NVIC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/RCC_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SEG_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/SysTick_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/DMA_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/TIM_Headers" -I"C:/Users/General/Documents/STM32CubeIDE/WorkSpaceNTI/Sensor_project/Inc/UART_Headers" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/sysmem.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

